##geeft alle clients
GET http://localhost:5000/api/v1/Clients
Content-Type: application/json
ApiToken:H8I9J10
###

##geeft bepaald aantal clients
GET http://localhost:5000/api/v1/Clients/limit/10
Content-Type: application/json
ApiToken: H8I9J10
###

##geeft bepaalde client
GET http://localhost:5000/api/v1/Clients/1
Content-Type: application/json
ApiToken: A1B2C3D4
###

##voegt client toe
POST http://localhost:5000/api/v1/Clients
Content-Type: application/json
ApiToken: A1B2C3D4

{
    "name": "John Test",
    "address": "123 Main St",
    "city": "Anytown",
    "zipCode": "12345",
    "province": "Zeeland",
    "country": "Netherlands",
    "contactName": "John Doe",
    "contactPhone": "+123456789",
    "contactEmail": "test2.doe@example.com"
}
###

##voegt client toe
POST http://localhost:5000/api/v1/Clients
Content-Type: application/json
ApiToken: A1B2C3D4

{
    "name": "Nick muik",
    "address": "123 Main St",
    "city": "Rotterdam",
    "zipCode": "1231231",
    "province": "Zuid-Holland",
    "country": "Netherlands",
    "contactName": "Nick Muik",
    "contactPhone": "+31231231",
    "contactEmail": "nickmuik@gmail.com"
}
###

##Andere data maar dezelfde email (Badrequest)
POST http://localhost:5000/api/v1/Clients
Content-Type: application/json
ApiToken: A1B2C3D4

{
    "name": "Vincent Stoel",
    "address": "123 Main St",
    "city": "Oosterland",
    "zipCode": "3123123",
    "province": "Zeeland",
    "country": "Netherlands",
    "contactName": "Vincent Stoel",
    "contactPhone": "+123456789",
    "contactEmail": "john.dtoe@example.com"
}
###

##update client
PUT http://localhost:5000/api/v1/Clients/1
Content-Type: application/json
ApiToken: E5F6G7

{
    "name": "Jane Doe",
    "address": "456 Secondary St",
    "city": "New City",
    "zipCode": "54321",
    "province": "Berlin",
    "country": "Germany",
    "contactName": "Jane Doe",
    "contactPhone": "+987654321",
    "contactEmail": "jane.doe@example.com"
}
###

##verwijdert client
DELETE http://localhost:5000/api/v1/Clients/1/test
Content-Type: application/json
ApiToken: A1B2C3D4
###
