##geeft alle clients
GET http://localhost:5000/api/v1/suppliers
Content-Type: application/json
###

//geeft bepaalde client
GET http://localhost:5000/api/v1/suppliers/1
Content-Type: application/json
###
//voegt client toe
POST http://localhost:5000/api/v1/suppliers
Content-Type: application/json

{
    "code": "WH0010",
    "name": "Test Warehouse",
    "address": "123 Test Lane",
    "zipCode": "12345",
    "city": "TestCity",
    "province": "TestProvice",
    "country": "TestCountry",
    "contactName": "John Doe",
    "phoneNumber": "555-1234",
    "reference": "SPR-9999"
}        

###
//voegt client toe
# POST http://localhost:5000/api/v1/Clients
# Content-Type: application/json

# {
#     "name": "Nick muik",
#     "address": "123 Main St",
#     "city": "Rotterdam",
#     "zipCode": "1231231",
#     "province": "Zuid-Holland",
#     "country": "Netherlands",
#     "contactName": "Nick Muik",
#     "contactPhone": "+31231231",
#     "contactEmail": "nickmuik@gmail.com"
# }
###
//Andere data maar dezelfde email (Badrequest)
POST http://localhost:5000/api/v1/suppliers
Content-Type: application/json

{
    "code": "WH0010",
    "name": "Test Warehouse",
    "address": "123 Test Lane",
    "zipCode": "12345",
    "city": "TestCity",
    "province": "TestProvice",
    "country": "TestCountry",
    "contactName": "John Doe",
    "phoneNumber": "555-1234",
    "reference": "SPR-9999"
}   
###
//update client
PUT http://localhost:5000/api/v1/suppliers/1
Content-Type: application/json

{
    "supplierId": 1,
    "code": "WH0010",
    "name": "Test Warehouse",
    "address": "123 Test Lane",
    "zipCode": "12345",
    "city": "TestCity",
    "province": "TestProvice",
    "country": "TestCountry",
    "contactName": "John Doe",
    "phoneNumber": "555-1234",
    "reference": "SPR-9999"
}   

###
//verwijdert client
DELETE http://localhost:5000/api/v1/suppliers/9821
Content-Type: application/json
####