###
POST http://localhost:5000/api/v1/warehouses
Content-Type: application/json

{
  "code": "WH003",
  "name": "Main Warehouse",
  "address": "123 Warehouse Lane",
  "zip": "12345",
  "city": "CityName",
  "province": "ProvinceName",
  "country": "CountryName",
  "contactName": "John Doe",
  "contactPhone": "555-1234",
  "contactEmail": "johndoe@example.com"
}
####

GET http://localhost:5000/api/v1/warehouses
####

GET http://localhost:5000/api/v1/warehouses/1
####

PUT http://localhost:5000/api/v1/warehouses/1
Content-Type: application/json

{
  "code": "WH001",
  "name": "Updated Warehouse Name",
  "address": "456 New Address Blvd",
  "zip": "67890",
  "city": "NewCity",
  "province": "NewProvince",
  "country": "NewCountry",
  "contactName": "Jane Smith",
  "contactPhone": "555-6789",
  "contactEmail": "jane.smith@example.com"
}
####

DELETE http://localhost:5000/api/v1/warehouses/5
####
