name: CargoHub Refactor Workflow

on:
  push:
    branches: 
        - main
        - Development
  pull_request:
    branches: 
        - main
        - Development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests

      - name: Restore dependencies
        run: |
          dotnet restore
        working-directory: CargoHubRefactor

      - name: Build
        run: dotnet build --no-restore
        working-directory: CargoHubRefactor

      - name: Test Refactor
        run: |
          dotnet run &
          pytest
        working-directory: CargoHubRefactor

      # - name: Test Refactor
      #   run: dotnet test --verbosity normal
      #   working-directory: CargoHubRefactorTesting